// <auto-generated />
using System;
using LeadsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadsApi.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Plumbing",
                            DateCreated = new DateTime(2025, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kitchen leak",
                            Email = "ana@example.com",
                            FirstName = "Ana",
                            LastName = "Silva",
                            Phone = "(31) 99999-1111",
                            Price = 650.00m,
                            Status = 0,
                            Suburb = "Centro"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electrical",
                            DateCreated = new DateTime(2025, 9, 2, 15, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Outlet repair",
                            Email = "bruno@example.com",
                            FirstName = "Bruno",
                            LastName = "Souza",
                            Phone = "(31) 98888-2222",
                            Price = 300.00m,
                            Status = 0,
                            Suburb = "Savassi"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cleaning",
                            DateCreated = new DateTime(2025, 9, 3, 9, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Post-renovation",
                            Email = "carla@example.com",
                            FirstName = "Carla",
                            LastName = "Lima",
                            Phone = "(31) 97777-3333",
                            Price = 800.00m,
                            Status = 1,
                            Suburb = "Funcionários"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
